### ISSUE TITLE
1.16.2: How to send commands in arena.yml from console?

### ISSUE THREAD

**Issue by kev2k2de** [kangarko/CoreArena#338]
When I set commands in the rewards section of an arena, tey are sent by the player and not by the console.
I tried a few things but I didn´t get a solution.

My rewards section:
https://hastebin.com/egenajaxey.makefile

**Comment by AngellitoX** [comment]
Hello there, the format you need to use is the following example:


````
# Rewards players will earn after the arena has finishes
Rewards:
  Waves:
    Every:
      15: iron_ingot:16, gold_ingot:8, diamond:1
    After:
      13: iron_sword, iron_pickaxe, iron_spade
      50: cmd(x1 Dungeon Key):/cc give physical dungeons 1 <player>
```` 

Hope that helps you! I'm marking this as solved for now.
Angel from MineAcademy.org

**Comment by kev2k2de** [comment]
This still doesn´t work, with that configuration I don´t get anything.
Also, there is a different/new configuration when I create a new Arena, which runs the commands by the player.
This just doesn´t make sense to me.

```
#
# Rewards to give on every nth wave or after a certain wave
# This is a list containing either items:amounts or commands 
#
Rewards: 

###given by server/console:###
  Every:
    5: 
    - "iron_ingot:16"
    - "gold_ingot:8"
    - "diamond:1"
  At: 
    10: 
    - "iron_sword"
    - "iron_pickaxe"
    - "iron_spade"

###run by player: ###    
    20: 
    - "/cc give physical dungeons 1 {player}"
```
