### ISSUE TITLE
Player Expereince kill drops do not work!!!

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#367]
I am setting up a PVP mob arena and I tried increasing the amount player kills drop XP:
```
Experience:
  Next_Phase: "5 + (5 * {phase})"
  Kill:
    Global: "35 + (5 * {phase})"
    Player: "500 + (6 * {phase})"
    CREEPER: "100 + (5 * {phase})"
```

I tried this in both settings.yml and the arena yml file and changing the Player: key has no effect at all. Changing global seems to work but that's global which I don't want, I simply want to change the amount of XP that players get when killing each other.

**My Diagnosis:** I think `CoreArena is not detecting when a player kills another player` for some reason, could we have this fixed?

**Evidence:** As you can see in this photo, ChatControlPro detects it as a player kill, but CoreAreena does not:
[player-kill-xp-not-working.png](https://postimg.cc/d7KVWNdB)

I suppose the event listener that listens for players killing other players works for ChatControlPro, but not CoreArena, hopefully it's a simple as copying a portion of ChatControls code and sticking it into CoreArenas code... that didn't make much sense but or well 😂

Thanks!
