### ISSUE TITLE
Mob spawner clone tool is broken when using CoreArena Eggs or Boss Eggs!

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/CoreArena#368]
Using Latest CoreArena and PaperMC
Here is the error message:
https://pastebin.com/EXXhB1SS

It does not happen when I place vanilla eggs inside the spanner, it only happens when using CoreArena Eggs or Boss eggs.

`ClassCastException java.lang.String cannot be cast to java.util.Map `

Not sure what that part of the error means, perhaps a mismatch of data types (String)? I have no clue lol

Thanks in advanced! I hope this is fixed as manually making each spawner takes a REALLY long time...

**Comment by kangarko** [comment]
Hi there!

Thank you for reporting. Unfortunately Spigot/Bukkit can't properly save custom ItemStack which, CoreArena eggs or Boss eggs use. So we'd have to implement our own system which would be too extensive and break with every release, hence we do not offer clone tool support for spawners with custom itemstacks.

Matej

**Comment by LeehamElectronics** [comment]
Really? It use to work just fine in the past, I have been using the mob client tool for ages with custom eggs, it only just stoped working recently, are you sure there isn't another way around this?? 

Like I said it's really breaking having to manually make all mob spawners, and it use to work fine in the past...

Thanks @kangarko

**Comment by LeehamElectronics** [comment]
I understand your reasoning, however let me propose a solution
CoreArena saves monster spawners in the data.db like so:
```
   - location: MobArena -396 6 274
        activePeriod:
          mode: 'on'
          limit: 1
          limit2: 1
        minPlayers: 1
        chance: 100
        spawnAllSlots: false
        spawns:
        - custom_egg:
            ==: org.bukkit.inventory.ItemStack
            v: 2580
            type: CREEPER_SPAWN_EGG
            amount: 3
            meta:
              ==: ItemMeta
              meta-type: SPAWN_EGG
              display-name: Spawn SuperCreeper
              lore:
              - '§7 '
              - §2§l< §7Left click for menu
              - §2§l> §7Right click to summon
              enchants:
                DURABILITY: 1
              ItemFlags:
              - HIDE_ENCHANTS
              - HIDE_ATTRIBUTES
              - HIDE_UNBREAKABLE
              - HIDE_DESTROYS
              - HIDE_PLACED_ON
              - HIDE_POTION_EFFECTS
              internal: H4sIAAAAAAAAAONiYOBiYPNOdMovLuZgYMlLzE1l4AkuLUgtci5KTQVSDAwAy5zhvSMAAAA=
```

When using the clone spawner tool, can CoreArena get the spawner data straight from the data.db file, store it in RAM, and then when players clone a spawner it simply duplicates the data stored in data.db with a different` location: ` and appends it to the data.db? I don't think you need to have the 'custom itemstack' saved in Spigots block information or whatever (I don't really know how it works) but from my programming experience it should be possible to read the spawner from the yml data.db and duplicate it with the new location taken from the player placing the spawner block.

I hope that made a bit of sense.
