### ISSUE TITLE
Experience per arena

### ISSUE THREAD

**Issue by BlueSoapTurtle** [kangarko/CoreArena#60]
```
Experience:
  Exp_Per_Level: 40
  Level_To_Nugget_Conversion_Ratio: 1.0
  Item: INK_SACK:12
  Item_Label: '&b{amount} exp'
  Gold:
    Conversion_Ratio: 100
    Currency_Backup_Name: $
  Amount:
    Next_Phase: 5 + (5 * {phase})
    Kill:
      Global: 10 + (5 * {phase})
      Player: 30 + (6 * {phase})
      CREEPER: 15 + (5 * {phase})
      SILVERFISH: 5 + (3 * {phase})
```
Could you possible move parts of this to the arena so we can make arena 3 give more exp than arena 1?
